# Generated by Django 5.0.4 on 2024-04-06 22:42

import events_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/'),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='upload',
            field=models.FileField(upload_to=events_application.models.upload_to_event_directory),
        ),
    ]
