# Generated by Django 5.0.4 on 2024-04-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_application', '0002_event_cover_photo_alter_mediaupload_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to='event_covers/'),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='upload',
            field=models.FileField(upload_to='events/'),
        ),
    ]
