# Generated by Django 5.0.4 on 2024-04-07 00:17

import events_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_application', '0003_alter_event_cover_photo_alter_mediaupload_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='upload',
            field=models.FileField(upload_to=events_application.models.upload_to_event_directory),
        ),
    ]
