# Generated by Django 5.0.4 on 2025-03-31 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_application', '0004_alter_mediaupload_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_uploads', to='events_application.event'),
        ),
    ]
